version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: document
    ports:
      - "3306:3306"
    command: ["--innodb-force-recovery=0"]
    volumes:
      - ./tmp/db:/var/lib/mysql
      
  web:
    # platform: linux/amd64
    # image: phamthiminhthu2k0/docskanry
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/document?user=root&password=password&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false"