server:
    port: ${SERVER_PORT}
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driverClassName: ${DRIVER_CLASSNAME}
        url: ${DB_URL}
        username: ${DB_NAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: ${MAIL_HOST}
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: ${MAIL_HOST}
    servlet:
        multipart:
            max-file-size: ${MAX_FILE-SIZE}
            max-request-size: ${MAX_REQUEST_SIZE}
    profiles:
        active: production
amazonProperties:
    endpointUrl: ${ENDPOINT_URL}
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    bucketName: ${BUCKET_NAME}
    region:  ${REGION}
google:
    scholar:
        api:
            key: ${GOOGLE_SCHOLAR_KEY}