server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/document
        username: ${DB_NAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.office365.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: smtp.office365.com

amazonProperties:
    endpointUrl: https://s3.us-east-2.amazonaws.com
    accessKey: AKIAWAFVB6T3BZW7HYBG
    secretKey: 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
    bucketName: bedocument